import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: "Next.js - Title Metadata",
    template: "%s | Title Metadata",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem"
          }}
        >HEADER
        </header>

        {children}

        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem"
          }}
        >FOOTER
        </footer>
      </body>
    </html>
  )
}
